### ISSUE TITLE
Repo not working

### ISSUE THREAD

**Issue by badyalkumar291** [Corymbia/eucalyptus#107]
This repo link is not working.
yum install http://downloads.eucalyptus.com/software/eucalyptus/nightly/4.4/rhel/7/x86_64/eucalyptus-release-nightly-4.4-1.el7.noarch.rpm

**Comment by sjones4** [comment]
Installs should use the regular release package rather than nightly:

```
yum install http://downloads.eucalyptus.cloud/software/eucalyptus/4.4/rhel/7/x86_64/eucalyptus-release-4.4-2.8.as.el7.noarch.rpm
```

As there are no plans to make nightly builds available we could remove the `Install Nightly Release Packages` page from the documentation to avoid confusion.

**Comment by badyalkumar291** [comment]
Hi,
We have production on 4.0.2 eucalyptus version.Now we are facing issue on one node controller and we need to install new node controller but we are unable to take eucalyptus repository. Thatsway reason, We need eucalyptus packages. please assist.

http://downloads.eucalyptus.com/software/eucalyptus/
http://downloads.eucalyptus.com/software/eucalyptus/3.4/rhel/6/x86_64/e
ucalyptus-release-4.0.el6.noarch.rpm

Please share repository link for eucalyptus 4.0.2

**Comment by sjones4** [comment]
Eucalyptus 4.0.2 is quite old and is not available on the eucalyptus.cloud site. We do host 4.1 and 4.2, but for these you'll need to manually edit the `/etc/yum.repos.d/eucalyptus.repo` file after installing to point to the downloads.eucalyptus.cloud location:

http://downloads.eucalyptus.cloud/software/eucalyptus/4.1/rhel/6/x86_64/eucalyptus-release-4.1-1.el6.noarch.rpm
http://downloads.eucalyptus.cloud/software/eucalyptus/4.2/rhel/6/x86_64/eucalyptus-release-4.2-1.el6.noarch.rpm

For 4.3 we provided an updated release rpm that has the new repository location:

http://downloads.eucalyptus.cloud/software/eucalyptus/4.3/rhel/7/x86_64/eucalyptus-release-4.3-2.9.as.el7.noarch.rpm

**Comment by sjones4** [comment]
Closing this issue as docs are updated to remove references to nightly releases.
