### ISSUE TITLE
installion issue

### ISSUE THREAD

**Issue by badyalkumar291** [Corymbia/eucalyptus#108]
We are unable to install eucalyptus as per installion guide because repository link not working.Please assist.How we can take eucalyptus packages.

link not working  yum install http://downloads.eucalyptus.com/software/eucalyptus/nightly/4.4/rhel/7/x86_64/eucalyptus-release-nightly-4.4-1.el7.noarch.rpm

**Comment by sjones4** [comment]
Please use the installation guide found here:

https://docs.eucalyptus.cloud/eucalyptus/4.4.4/index.html#shared/install_section.html

and use the release package described in:

https://docs.eucalyptus.cloud/eucalyptus/4.4.4/index.html#install-guide/installing_euca_release.html

i.e.

```
yum install http://downloads.eucalyptus.cloud/software/eucalyptus/4.4/rhel/7/x86_64/eucalyptus-release-4.4-2.8.as.el7.noarch.rpm
```

There are not currently any nightly builds available.
