### ISSUE TITLE
Enable wiki into forked one

### ISSUE THREAD

**Issue by ramlaxman** [Corymbia/eucalyptus#146]
@Corymbia Kindly enable wiki in this repository as it is valuable information and it will be easy to contribute further.

**Comment by sjones4** [comment]
The old eucalyptus wiki has some useful information but also has a lot of out of date content. At some point selected content from the old wiki may be moved to a new format, but there is no short term plan to do so.

If you have a specific contribution in mind perhaps it may be suitable for the blog or documentation.
