### ISSUE TITLE
bug in docs for network json file

### ISSUE THREAD

**Issue by richwolski** [Corymbia/eucalyptus#154]
When creating a network.json file, it is useful to be able to cut and paste the example from the docs and then to modify it with the local specifics (IPs address, subnets, etc.)  The exmaple for a single cluster in the doc

https://docs.eucalyptus.cloud/eucalyptus/4.4.5/index.html#install-guide/nw_edge.html

has a comma after the first element of the clusters array indicating that there will be another cluster (like in the second example).  This comma causes euctl cloud.network.configuration to fail to parse the json.

**Comment by sjones4** [comment]
Fix merged. This change will be published if we rebuild/deploy the 4.4 docs.
