### ISSUE TITLE
Impossible to launch instance from "instance" view

### ISSUE THREAD

**Issue by evadim** [Corymbia/eucalyptus#157]
Eucalyptus v5 Installed via FastStart. When select EMI image on **Instances** tab, got error:
```
Image ID must be 12 alphanumeric characters and begin with 'emi-' or 'ami-'.
```
However, launch from **Images** tab work fine.

![ID error](https://user-images.githubusercontent.com/9168429/67640839-ce260500-f90d-11e9-9736-513f9078e396.png)

**Comment by sjones4** [comment]
As a work around for this issue you can switch to using short identifiers and then re-register the images:

```
# euctl cloud.short_identifier_prefixes='*'
```

if you wanted to use short identifiers only for images then use `emi` instead of `*`.

```
#
# euca-describe-images emi-d0314c733319a2ad4
IMAGE	emi-d0314c733319a2ad4	centos-7-11-01-17/CentOS-7-x86_64-GenericCloud-1801-01.raw.manifest.xml	000819487039	available	public	x86_64	machine				instance-store	hvm	
#
#
# euca-register -n centos-7-11-01-17-short --arch x86_64 --virt hvm centos-7-11-01-17/CentOS-7-x86_64-GenericCloud-1801-01.raw.manifest.xml
IMAGE	emi-92c1d2d5
#
#
# euca-modify-image-attribute -l -a all emi-92c1d2d5
launchPermission	emi-92c1d2d5	ADD	Group	all
#
```

**Comment by evadim** [comment]
Launch from Images tab also works fine, so I can use long identifiers in GUI.
