### ISSUE TITLE
cluster not working

### ISSUE THREAD

**Issue by anmol-shukla** [Corymbia/eucalyptus#174]
I am not installing the cloud using faststart. It is just the regular installation.
I have run euserv-describe-services and it is showing that cluster is not ready.
Also the file cluster-cert.pem is not present. how can I get it.
I am also not being able to understand the steps for configuring master DNS server.

**Comment by sjones4** [comment]
You may have missed the `clcadmin-copy-keys` step:

> Copy the security credentials from the CLC to each machine running Cluster Controller services. 
> Run this command on the CLC host machine:
> 
>     clcadmin-copy-keys -z ZONE HOST
http://docs.eucalyptus.cloud/eucalyptus/4.4.5/index.html#install-guide/registering_ccs.html

You can use the [eucalyptus tag on stackoverflow](https://stackoverflow.com/questions/tagged/eucalyptus) for questions, github issues are for bug/issue reports.

**Comment by anmol-shukla** [comment]
i did it but still the same result
