### ISSUE TITLE
management console prob

### ISSUE THREAD

**Issue by anmol-shukla** [Corymbia/eucalyptus#175]
I have installed cloud using faststart and after installation I was able to access the management console at first.
but i restarted the system on which cloud was installed and after that i cant access the management console.
Please help

**Comment by sjones4** [comment]
If `journalctl -u eucaconsole.service` shows output such as `eucaconsole[3120]: Starting eucaconsole nginx:`, i.e without an ending `[  OK  ]` on the line then you may need to update `/etc/rc.d/init.d/eucaconsole` as per:

https://github.com/AppScale/ats-deploy/blob/90e94fbe503a5c0b1a6cdb3100af0c22959d5b7f/roles/console/tasks/main.yml#L41:L45

so you end up with:

```
daemon --pidfile ${NGINXPIDFILE} /usr/sbin/nginx -c /etc/eucaconsole/nginx.conf $NGINX_FLAGS
```

the `--pidfile ${NGINXPIDFILE}` option is not present in the installed file.

If you still have issues then the `journalctl -u eucaconsole.service` output and any errors from `/var/log/eucaconsole.log` and `/var/log/nginx/eucaconsole_nginx_error.log` would help determine the cause.
