### ISSUE TITLE
Euca 5 Ansible Console Image Install Order

### ISSUE THREAD

**Issue by ndtroubleshoot** [Corymbia/eucalyptus#246]
When using the Ansible installer and choosing to install a cloud based console image the ansible task hangs the entire install. Based on the playbook output no action is taken to configure node controllers before the service image task is started. I am guessing there are no virtualization services available on which to deploy the console image? Is this broken? inventory.yml below

TASK [cloud : install service image as system image] .....

---
all:
  hosts:
    host-euca.local.com:
    host-enc-[01:02].local.com:

  vars:
    vpcmido_public_ip_range: "192.168.100.5-192.168.100.254"
    vpcmido_public_ip_cidr: "192.168.100.1/24"
    cloud_system_dns_dnsdomain: "cloud.local.com"
    cloud_public_port: 443
    eucalyptus_console_cloud_deploy: yes
    cloud_service_image_rpm: no
    cloud_properties:
      services.imaging.worker.ntp_server: "time.cloudflare.com"
      services.loadbalancing.worker.ntp_server: "time.cloudflare.com"

  children:
    cloud:
      hosts:
        host-euca.local.com:
    zone:
      hosts:
        host-euca.local.com:
    nodes:
      hosts:
        host-enc-[01:02].local.com:

**Comment by sjones4** [comment]
The `install service image as system image` section is attempting to download an image from `downloads.eucalyptus.cloud` and upload to the clouds s3 service. You can try this manually for troubleshooting (as root):

```
eval $(clcadmin-assume-system-credentials)
/usr/local/bin/eucalyptus-system-images --type service
```

It is not expected that node controllers are available, only the s3 service.

**Comment by ndtroubleshoot** [comment]
Thanks that solves it. It’s probably a proxy issue in that case.

Would you know is there a best place to globally set the proxy environment
for all plays or should I just set it at each task that may need it?

**Comment by sjones4** [comment]
I'm not sure how to best configure the installer for a proxy.

If there are simple changes to the playbook to better support this use case then it would be good to include them.
