### ISSUE TITLE
Installation Unavailable...

### ISSUE THREAD

**Issue by lesparker** [Corymbia/eucalyptus#269]
Error downloading packages:
  eucalyptus-release-5-1.15.as.el7.noarch: [Errno 256] No more mirrors to try.

Please advise.

Thank you!

Les

les@indoorlogic.com

P.S.

Any news on an alternate installation platform since Centos7 has been discontinued?

**Comment by sjones4** [comment]
For eucalyptus 5.x releases on RHEL/CentOS 7.9:

```
yum install https://downloads.eucalyptus.cloud/software/eucalyptus/5/rhel/7/x86_64/eucalyptus-release-5-1.11.as.el7.noarch.rpm
```

**Comment by lesparker** [comment]
yum install https://downloads.eucalyptus.cloud/software/eucalyptus/5/rhel/7/x86_64/eucalyptus-release-5-1.11.as.el7.noarch.rpm
Loaded plugins: copr, fastestmirror, langpacks, product-id, search-disabled-repos
eucalyptus-release-5-1.11.as.el7.noarch.rpm                                                                                       | 6.9 kB  00:00:00     
Examining /var/tmp/yum-root-JA_4nu/eucalyptus-release-5-1.11.as.el7.noarch.rpm: eucalyptus-release-5-1.11.as.el7.noarch
/var/tmp/yum-root-JA_4nu/eucalyptus-release-5-1.11.as.el7.noarch.rpm: does not update installed package.
Error: Nothing to do

**Comment by lesparker** [comment]
rpm -qlp eucalyptus-release-5-1.11.as.el7.noarch.rpm
/etc/pki/rpm-gpg/RPM-GPG-KEY-eucalyptus-release
/etc/pki/rpm-gpg/RPM-GPG-KEY-eucalyptus-release-as
/etc/yum.repos.d/eucalyptus.repo
