### ISSUE TITLE
How to get that sweet underline hyperlink animation seen in the docs page?

### ISSUE THREAD

**Issue by openSourcerer9000** [Corymbia/eucalyptus#341]
This underline hyperlinks on hover thing in the documentation page is badass, how was this done?

https://docs.eucalyptus.cloud/eucalyptus/5/user_guide/
![image](https://user-images.githubusercontent.com/61931826/184444345-4a431450-ee08-42b3-9338-d8d83df26f84.png)

**Comment by 0xfrej** [comment]
Like [this](https://jsfiddle.net/lai0n/zmdqp67o/9/ ). It's inspired by the version of the effect in the docs.

**Comment by openSourcerer9000** [comment]
Nice and simple love it
